### ISSUE TITLE
Camera bị load lại hoài mỗi khi back từ view 1 cam -> tốn data

### ISSUE THREAD

**Issue by ghost** [ducminhquan/ttgt-issues#1]
![screenshot_20170217-162624](https://cloud.githubusercontent.com/assets/8115768/23059906/fd5a70ae-f52d-11e6-9d8d-6f5cccbacbd6.png)

**Comment by ducminhquan** [comment]
Đã cập nhật trong build ```3.0.21```.
Đang chuyển qua openbeta, chắc tối có nha anh @duynguyendang.
